name: state_management
description: Application for different forms of state management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  meta: ^1.1.8
  equatable: ^1.2.5

  bloc: ^6.1.0
  flutter_bloc: ^6.1.1

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4

  google_sign_in: ^4.5.6
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.4.0

  formz: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
